name: Bug Report
description: Report bugs in the code
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Before opening a new issue, please search existing issues:  https://github.com/gta-reversed/gta-reversed-modern/issues"
  - type: textarea
    id: expected
    attributes:
      label: Expected and current behavior
      description: Concise description of the the behavior you expect and the one that actually occurs.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: If you have anything else to add that you consider to be useful, please type it here.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear and concise steps for us to reliably reproduce this issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Provide a screenshot and/or video demonstrating the issue being experienced.
    validations:
      required: false
